# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f3876b8fcce4a3a193bb25874131f68dd33a3d91df90d74459bc3f000ab25b5162ab5344359ff0a759435ccebb0866487506956f132c247938fc34dae70d4310

test:
  secret_key_base: 5f147e73dc553d4087fc7971c9e5e936d9c0293df196f60870388794ae3b07f97aa8221eed957142f35cf979c40fc66a38922b7a60769b822f269a3760edcd4e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
